use_frameworks!

platform :ios, '8.0'

target 'FSNetwork_Example' do
  pod 'FSNetwork', :path => '../'

  target 'FSNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'
  end
end
